# Generated by Django 3.2.23 on 2024-02-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20231104_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='category',
            field=models.CharField(choices=[('ADMINISTRATION', 'Administration'), ('COMMUNICATION', 'Kommunikation'), ('MANAGEMENT', 'Verwaltung'), ('DISPOSITION', 'Disposition'), ('CLOUD', 'Cloud')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
