# Generated by Django 3.2.23 on 2024-02-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_log_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='category',
            field=models.CharField(choices=[('SYSTEM', 'System'), ('ADMINISTRATION', 'Administration'), ('COMMUNICATION', 'Kommunikation'), ('MANAGEMENT', 'Verwaltung'), ('DISPOSITION', 'Disposition'), ('CLOUD', 'Cloud')], max_length=20),
        ),
    ]
