# Generated by Django 3.2.23 on 2024-03-10 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0015_auto_20231123_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signature',
            old_name='show_Location',
            new_name='show_location',
        ),
    ]
